nodeLinker: hoisted

allowBuilds:
  core-js: false
  electron: true
  electron-winstaller: true

blockExoticSubdeps: false

minimumReleaseAge: 0

ignoredBuiltDependencies:
  - core-js
  - electron
  - electron-winstaller
